export interface Category {
  slug: string;
  name: string;
  shortName: string;
  summary: string;
  imageUrl: string;
}

export interface Product {
  slug: string;
  categorySlug: string;
  section: 'ppe' | 'fire-service';
  name: string;
  shortDescription: string;
  description: string;
  imageUrl: string;
  features: string[];
  applications: string[];
}

export interface Promotion {
  eyebrow: string;
  title: string;
  description: string;
  imageUrl: string;
  cta: string;
}

const ppeAsset = (fileName: string): string => `/assets/PPE/${fileName}`;
const iconAsset = (fileName: string): string => `/assets/icon/${fileName}`;

export const ppeCategories: Category[] = [
  {
    slug: 'head-protection',
    name: 'Head Protection',
    shortName: 'Head',
    summary: 'Helmets, bump caps, and head protection accessories.',
    imageUrl: iconAsset('icon_Head_Protection.png'),
  },
  {
    slug: 'foot-protection',
    name: 'Foot Protection',
    shortName: 'Foot',
    summary: 'Safety footwear for industrial, electrical, and site operations.',
    imageUrl: iconAsset('icon_Foot_Protection.png'),
  },
  {
    slug: 'eye-protection',
    name: 'Eye Protection',
    shortName: 'Eye',
    summary: 'Safety glasses and goggles for impact, dust, and splash protection.',
    imageUrl: iconAsset('icon_Eye_Protection.png'),
  },
  {
    slug: 'face-protection',
    name: 'Face Protection',
    shortName: 'Face',
    summary: 'Face shields and visors for cutting, grinding, and splash work.',
    imageUrl: iconAsset('icon_Face_Protection.png'),
  },
  {
    slug: 'respiratory-protection',
    name: 'Respiratory Protection',
    shortName: 'Respiratory',
    summary: 'Respirators, masks, cartridges, and filters.',
    imageUrl: iconAsset('icon_Respiratory_Protection.png'),
  },
  {
    slug: 'hearing-protection',
    name: 'Hearing Protection',
    shortName: 'Hearing',
    summary: 'Ear plugs and ear muffs for noisy work zones.',
    imageUrl: iconAsset('icon_Hearing_Protection.png'),
  },
  {
    slug: 'hand-protection',
    name: 'Hand Protection',
    shortName: 'Hand',
    summary: 'Gloves for cut, chemical, heat, and general handling risks.',
    imageUrl: iconAsset('icon_Hand_Protection.png'),
  },
  {
    slug: 'body-protection',
    name: 'Body Protection',
    shortName: 'Body',
    summary: 'Coveralls, reflective clothing, aprons, and protective garments.',
    imageUrl: iconAsset('icon_Body_Protection.png'),
  },
  {
    slug: 'fire-protection',
    name: 'Fire Protection',
    shortName: 'Fire',
    summary: 'Fire blankets, cabinets, signs, and support equipment.',
    imageUrl: iconAsset('icon_Fire_Protection.png'),
  },
  {
    slug: 'fall-arrest-equipment',
    name: 'Fall Arrest Equipment',
    shortName: 'Fall Arrest',
    summary: 'Harnesses, lanyards, lifelines, and anchors for work at height.',
    imageUrl: iconAsset('icon_Fall_Arrest_Equipment.png'),
  },
  {
    slug: 'emergency-equipment',
    name: 'Emergency Equipment',
    shortName: 'Emergency',
    summary: 'Emergency response products for factories and work sites.',
    imageUrl: iconAsset('icon_Emergency_Equipment.png'),
  },
  {
    slug: 'spill-control',
    name: 'Spill Control',
    shortName: 'Spill',
    summary: 'Absorbents, spill kits, and containment supplies.',
    imageUrl: iconAsset('icon_Spill_Control.png'),
  },
  {
    slug: 'other',
    name: 'Other',
    shortName: 'Other',
    summary: 'Additional safety items and site support products.',
    imageUrl: iconAsset('icon_Other.png'),
  },
];

export const fireServiceCategories: Category[] = [
  {
    slug: 'fire-extinguisher',
    name: 'Fire Extinguisher',
    shortName: 'Fire Extinguisher',
    summary: 'Portable extinguishers for factories, offices, vehicles, and warehouses.',
    imageUrl: iconAsset('icon_Fire_Extinguisher.png'),
  },
  {
    slug: 'refill-service',
    name: 'Refill Service',
    shortName: 'Refill Service',
    summary: 'Inspection, refilling, pressure checks, service tags, and audit-ready records.',
    imageUrl: iconAsset('icon_Refill_Service.png'),
  },
];

export const categories: Category[] = [...ppeCategories, ...fireServiceCategories];

export const promotions: Promotion[] = [
  {
    eyebrow: 'Uplix Safety',
    title: 'Industrial PPE and safety supply',
    description: 'Select protection by risk category and view product details for purchasing or quotation.',
    imageUrl: '/assets/fire_tank/fire-training-hero.jpg',
    cta: 'Browse PPE',
  },
  {
    eyebrow: 'Fire Protection',
    title: 'Fire extinguisher and refill service',
    description: 'Equipment, refill, inspection, and service records for workplace fire readiness.',
    imageUrl: '/assets/fire_tank/firefighting.jpg',
    cta: 'View service',
  },
];

interface PpeProductGroup {
  categorySlug: string;
  folder: string;
  files: readonly string[];
}

const ppeProductGroups: readonly PpeProductGroup[] = [
  {
    categorySlug: 'body-protection',
    folder: 'Body_Protection',
    files: [
      'BDP1000.png',
      'BDP101.png',
      'BDP1013-1.png',
      'BDP101V.png',
      'BDP1020.png',
      'BDP1021.png',
      'BDP1030.png',
      'BDP106.png',
      'BDP1060-3.png',
      'BDP1200S3.png',
      'BDP1200S6.png',
      'BDP1201.png',
      'BDP1201-1P.png',
      'BDP1261.png',
      'BDP1261S3.png',
      'BDP1262.png',
      'BDP1263.png',
      'BDP1263S1AA.png',
      'BDP1264S1.png',
      'BDP1290.png',
      'BDP1300.png',
      'BDP1300S.png',
      'BDP1300SS.png',
      'BDP1301S.png',
      'BDP1350-1.png',
      'BDP1402.png',
      'BDP1403.png',
      'BDP1404S1.png',
      'BDP1601.png',
      'BDP2000-6.png',
      'BDP2003-2.png',
      'BDP2006.png',
      'BDP2040.png',
      'BDP2100RF.png',
      'BDP2120.png',
      'BDP2130.png',
      'BDP2133.png',
      'BDP2200.png',
      'BDP2202.png',
      'BDP2300-1.png',
      'BDP2303.png',
      'BDP2305-4.png',
      'BDP2314.png',
      'BDP2400.png',
      'BDP2400-1.png',
      'BDP2604M-1.png',
      'BDP2605.png',
      'BDP2606.png',
      'BDP2607.png',
      'BDP2610.png',
      'BDP2610S.png',
      'BDP2830-3.png',
      'BDP2831-6.png',
      'BDP2900.png',
      'BDP2902-3.png',
      'BDP5401.png',
      'BDP5403.png',
      'BDP5404.png',
      'BDP5600.png',
      'BDP5700.png',
      'BDP5701.png',
      'BDP8700-4.png',
      'BDP9602.png',
    ],
  },
  {
    categorySlug: 'emergency-equipment',
    folder: 'Emergency_Equipment',
    files: [
      'MN-1.png',
      'MN-100-RA.png',
      'MN-100-RA-G.png',
      'MN-100-RB.png',
      'MN-2.png',
      'MN-3-4.png',
      'MN-75-CA.png',
      'MN-75-CC.png',
      'MN-75-CD.png',
    ],
  },
  {
    categorySlug: 'fall-arrest-equipment',
    folder: 'Fall_Arrest_Equipment',
    files: [
      'FAH100016.png',
      'FAH100059.png',
      'FAH100069.png',
      'FAH300033.png',
      'FAHBK01.png',
      'FAHBK02.png',
      'FAHBK03.png',
      'FAL300004.png',
      'FAL300027.png',
      'FAL300212.png',
      'FAL312205.png',
      'FAL3211.png',
      'FAL322204.png',
      'FAL700 Series.png',
      'FAL800100.png',
      'FALKB01.png',
      'FALKB02.png',
      'FALSRL-40.png',
    ],
  },
  {
    categorySlug: 'fire-protection',
    folder: 'Fire_Protection',
    files: [
      'B613-1 & E604-1.png',
      'BDP1060-7240G.png',
      'BDP1300FR.png',
      'BDP2137.png',
      'BDP3001-1.png',
      'BDP3004.png',
      'BDP3105.png',
      'BDP3200.png',
      'BDP3207.png',
      'BDP3208.png',
      'BDP3407.png',
      'BDP3700.png',
      'BDP5000.png',
      'BDP504-S1.png',
      'BDP5050.png',
      'BDP5103.png',
      'BDP5200.png',
      'BDP5200-1.png',
      'BDP5220-1W.png',
      'BDP5220-2.png',
      'BDP5220-6.png',
      'BDP5220-7.png',
      'BDP5300.png',
      'BDP5304.png',
      'BDP5304-1.png',
      'BDP5310.png',
      'BDP5321.png',
      'BDP5324.png',
      'BDP5401.png',
      'BDP5500.png',
      'BDP5503.png',
      'BDP6000.png',
      'BDP6010.png',
      'BDP6030.png',
      'BDP6040-1.png',
      'BDP6080 (HG-3NF).png',
      'BDP6100.png',
      'BDP6120.png',
      'BDP7001-3.png',
      'BDP7006.png',
      'BDP7043WINTER.png',
      'BDP7101.png',
      'BDP7102.png',
      'BDP7303.png',
      'BDP7330.png',
      'BDP7332R.png',
      'BDP7334.png',
      'BDP7400.png',
      'BDP7402.png',
      'BDP7601.png',
      'BDP7602.png',
      'BDP7702.png',
      'BDP7706.png',
      'BDP821S-45.png',
      'BDP-BSH.png',
      'BDPFR28.png',
      'BDPFR68.png',
      'BP138.png',
      'BP140.png',
      'FR7402-1.png',
      'HDP7000-4.png',
      'HDP760.png',
      'ZFMH-DA C.png',
    ],
  },
  {
    categorySlug: 'foot-protection',
    folder: 'Foot_Protection',
    files: [
      'BM103.png',
      'BM103R3.png',
      'BM104.png',
      'FTP100.png',
      'FTP103.png',
      'FTP115.png',
      'FTP142.png',
      'FTP143.png',
      'FTP143RE.png',
      'FTP144.png',
      'FTP151.png',
      'FTP160.png',
      'FTP200.png',
      'FTP201.png',
      'FTP210.png',
      'FTP230.png',
      'FTP313.png',
      'FTP330.png',
      'FTP331.png',
      'FTP352.png',
      'FTP360.png',
      'FTP370.png',
      'FTP450.png',
      'FTP453.png',
      'FTP500.png',
      'FTP502.png',
      'FTP503.png',
    ],
  },
  {
    categorySlug: 'hand-protection',
    folder: 'Hand_Protection',
    files: [
      'HDP1021.png',
      'HDP1032DOTS.png',
      'HDP1032G13.png',
      'HDP1032G15.png',
      'HDP1033.png',
      'HDP1034.png',
      'HDP1042G10.png',
      'HDP1042G13.png',
      'HDP111.png',
      'HDP112.png',
      'HDP113.png',
      'HDP123G900.png',
      'HDP2011.png',
      'HDP2012.png',
      'HDP2013.png',
      'HDP2016.png',
      'HDP2024.png',
      'HDP2025.png',
      'HDP2026.png',
      'HDP2027.png',
      'HDP2032.png',
      'HDP-301-2.png',
      'HDP302.png',
      'HDP302WINTER.png',
      'HDP303.png',
      'HDP304.png',
      'HDP305.png',
      'HDP400.png',
      'HDP401.png',
      'HDP404.png',
      'HDP405.png',
      'HDP406BLA.png',
      'HDP501S1.png',
      'HDP501S14.png',
      'HDP501S2.png',
      'HDP501S4.png',
      'HDP501S5.png',
      'HDP501S6.png',
      'HDP501S7.png',
      'HDP501S8.png',
      'HDP501S9.png',
      'HDP601.png',
      'HDP602.png',
      'HDP603.png',
      'HDP624.png',
      'HDP701.png',
      'HDP711D300.png',
      'HDP711D500.png',
      'HDP712.png',
      'HDP713.png',
      'HDP801.png',
      'HDP802.png',
      'HDP803.png',
      'สกรีนช็อต 2026-03-25 164352.png',
      'สกรีนช็อต 2026-03-25 164400.png',
    ],
  },
  {
    categorySlug: 'spill-control',
    folder: 'Spill_Control',
    files: [
      'A2392H6T200W.png',
      'A2392T150.png',
      'ABB01G.png',
      'ABB01W.png',
      'ABB01Y.png',
      'ABM01G.png',
      'ABM01W.png',
      'ABM01Y.png',
      'ABP01G.png',
      'ABP01W.png',
      'ABP01Y.png',
      'ABR01G.png',
      'ABR01W.png',
      'ABR01Y.png',
      'ABS01G.png',
      'ABS01W.png',
      'ABS01Y.png',
      'AT200.png',
      'BBAGADULT400-300.png',
      'C2210H6T300.png',
      'C2210H6T500.png',
      'C2290T200.png',
      'CEARE 15.png',
      'KA1510H4T300J.png',
      'KA1510H6T200W.png',
      'KC1510H6T300 - Copy.png',
      'LDPE24413T500.png',
      'NH4120.png',
      'NT120.png',
      'NT1203D.png',
      'SKIT120LW.png',
      'SKIT30LG.png',
      'SKIT30LW.png',
      'W22578H6T185CHILE.png',
      'WT120.png',
      'WT120P.png',
    ],
  },
];

const fileNameToProductName = (fileName: string): string => fileName.replace(/\.[^.]+$/, '');

const slugify = (value: string): string =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const ppeImageAsset = (folder: string, fileName: string): string =>
  `/assets/PPE/${folder}/${encodeURIComponent(fileName)}`;

const ppeProducts: Product[] = ppeProductGroups.flatMap((group) =>
  group.files.map((fileName, index) => {
    const name = fileNameToProductName(fileName);
    const category = findCategory(group.categorySlug);

    return {
      slug: `${group.categorySlug}-${slugify(name) || 'item'}-${index + 1}`,
      categorySlug: group.categorySlug,
      section: 'ppe',
      name,
      shortDescription: category?.name ?? 'PPE',
      description: `${name} in ${category?.name ?? 'PPE'}.`,
      imageUrl: ppeImageAsset(group.folder, fileName),
      features: [name],
      applications: [category?.name ?? 'PPE'],
    };
  }),
);

const productSeed: Product[] = [
  {
    slug: 'protective-coverall',
    categorySlug: 'body-protection',
    section: 'ppe',
    name: 'BP-101',
    shortDescription: 'Disposable protective coverall',
    description: 'Disposable body protection for controlled areas, light industrial tasks, and visitor hygiene.',
    imageUrl: ppeAsset('body-protection-product.png'),
    features: ['Elastic cuff and hood', 'Lightweight breathable fabric', 'Bulk pack available'],
    applications: ['Factory visitor control', 'Food handling support', 'General hygiene zones'],
  },
  {
    slug: 'emergency-shower-station',
    categorySlug: 'emergency-equipment',
    section: 'ppe',
    name: 'EE-101',
    shortDescription: 'Emergency wash station',
    description: 'Emergency support equipment for immediate response in chemical and maintenance areas.',
    imageUrl: ppeAsset('emergency-equipment-product.png'),
    features: ['Clear emergency marking', 'Durable industrial hardware', 'Fast access design'],
    applications: ['Chemical handling', 'Maintenance areas', 'Production lines'],
  },
  {
    slug: 'anti-fog-safety-goggles',
    categorySlug: 'eye-protection',
    section: 'ppe',
    name: 'EP-101',
    shortDescription: 'Anti-fog safety goggles',
    description: 'Sealed goggles for impact, dust, and splash protection with clear peripheral visibility.',
    imageUrl: ppeAsset('eye-protection-product.png'),
    features: ['Anti-fog lens coating', 'Indirect ventilation', 'Comfortable elastic strap'],
    applications: ['Grinding and cutting', 'Lab handling', 'Chemical splash zones'],
  },
  {
    slug: 'clear-face-shield',
    categorySlug: 'face-protection',
    section: 'ppe',
    name: 'FP-101',
    shortDescription: 'Clear face shield',
    description: 'Face shield for splash, debris, and flying particle risks during industrial work.',
    imageUrl: ppeAsset('face-protection-product.png'),
    features: ['Wide clear visor', 'Adjustable headgear', 'Replaceable shield panel'],
    applications: ['Grinding', 'Chemical transfer', 'Maintenance work'],
  },
  {
    slug: 'full-body-safety-harness',
    categorySlug: 'fall-arrest-equipment',
    section: 'ppe',
    name: 'FA-101',
    shortDescription: 'Full body safety harness',
    description: 'Adjustable full body harness for roof, platform, scaffold, and elevated maintenance work.',
    imageUrl: ppeAsset('fall-arrest-equipment-product.png'),
    features: ['Dorsal D-ring', 'Quick adjustment buckles', 'Lanyard compatible'],
    applications: ['Roof maintenance', 'Scaffolding', 'Tank access'],
  },
  {
    slug: 'fire-blanket-cabinet',
    categorySlug: 'fire-protection',
    section: 'ppe',
    name: 'FR-101',
    shortDescription: 'Fire protection cabinet',
    description: 'Support fire protection equipment for emergency points and workplace readiness zones.',
    imageUrl: ppeAsset('fire-protection-product.png'),
    features: ['High visibility finish', 'Wall mount design', 'Easy access layout'],
    applications: ['Factory corridors', 'Warehouse exits', 'Emergency stations'],
  },
  {
    slug: 'safety-shoes',
    categorySlug: 'foot-protection',
    section: 'ppe',
    name: 'FT-101',
    shortDescription: 'Industrial safety shoes',
    description: 'Safety footwear for industrial, warehouse, and construction environments.',
    imageUrl: ppeAsset('foot-protection-product.png'),
    features: ['Toe protection', 'Slip resistant sole', 'Daily work comfort'],
    applications: ['Warehouse work', 'Construction sites', 'Production floors'],
  },
  {
    slug: 'cut-resistant-gloves',
    categorySlug: 'hand-protection',
    section: 'ppe',
    name: 'HP-101',
    shortDescription: 'Cut resistant gloves',
    description: 'Hand protection for assembly, metal handling, glass work, and packing lines.',
    imageUrl: ppeAsset('hand-protection-product.png'),
    features: ['Flexible knit liner', 'Grip coating', 'Multiple sizes'],
    applications: ['Metal sheets', 'Glass handling', 'Assembly lines'],
  },
  {
    slug: 'industrial-safety-helmet',
    categorySlug: 'head-protection',
    section: 'ppe',
    name: 'YY-101',
    shortDescription: '6-point hard hat',
    description: 'Lightweight hard hat with adjustable suspension for factory, construction, and maintenance teams.',
    imageUrl: ppeAsset('head-protection-product.png'),
    features: ['6-point suspension', 'Accessory slots', 'High visibility options'],
    applications: ['Construction zones', 'Factory maintenance', 'Warehouse operations'],
  },
  {
    slug: 'ear-muff-protection',
    categorySlug: 'hearing-protection',
    section: 'ppe',
    name: 'HR-101',
    shortDescription: 'Industrial ear muff',
    description: 'Hearing protection for teams working around machinery, compressors, and high-noise equipment.',
    imageUrl: ppeAsset('hearing-protection-product.png'),
    features: ['Padded ear cups', 'Adjustable headband', 'Reusable design'],
    applications: ['Machine rooms', 'Metal work', 'Production lines'],
  },
  {
    slug: 'safety-signage',
    categorySlug: 'other',
    section: 'ppe',
    name: 'OT-101',
    shortDescription: 'Safety signage and accessories',
    description: 'Additional safety support items for site communication, marking, and controlled access.',
    imageUrl: ppeAsset('other-product.png'),
    features: ['Clear visual marking', 'Indoor and outdoor options', 'Custom set planning'],
    applications: ['Site safety points', 'Visitor routes', 'Restricted zones'],
  },
  {
    slug: 'half-face-respirator-kit',
    categorySlug: 'respiratory-protection',
    section: 'ppe',
    name: 'RP-101',
    shortDescription: 'Half face respirator kit',
    description: 'Reusable respirator for dust, paint, vapor, chemical handling, and maintenance environments.',
    imageUrl: ppeAsset('respiratory-protection-product.png'),
    features: ['Soft face seal', 'Dual cartridge design', 'Replaceable filters'],
    applications: ['Painting areas', 'Chemical storage', 'Dust control work'],
  },
  {
    slug: 'spill-response-kit',
    categorySlug: 'spill-control',
    section: 'ppe',
    name: 'SC-101',
    shortDescription: 'Spill response kit',
    description: 'Spill control supplies for containment and cleanup of workplace liquid leaks.',
    imageUrl: ppeAsset('spill-control-product.png'),
    features: ['Absorbent pads and socks', 'Portable container', 'Clear emergency labeling'],
    applications: ['Chemical storage', 'Maintenance areas', 'Loading bays'],
  },
  {
    slug: 'abc-dry-chemical-extinguisher',
    categorySlug: 'fire-extinguisher',
    section: 'fire-service',
    name: 'FE-101',
    shortDescription: 'ABC dry chemical extinguisher',
    description: 'General-purpose portable extinguisher for office, warehouse, vehicle, and factory use.',
    imageUrl: '/assets/fire_tank/firefighting.jpg',
    features: ['Pressure gauge', 'Wall bracket included', 'Multiple capacities'],
    applications: ['Office corridors', 'Warehouses', 'Vehicle safety points'],
  },
  {
    slug: 'co2-fire-extinguisher',
    categorySlug: 'fire-extinguisher',
    section: 'fire-service',
    name: 'FE-102',
    shortDescription: 'CO2 fire extinguisher',
    description: 'Clean agent style extinguisher support for electrical equipment and sensitive work areas.',
    imageUrl: '/assets/fire_tank/fire-training-hero.jpg',
    features: ['Residue-free discharge', 'Electrical equipment use', 'Durable cylinder'],
    applications: ['Server rooms', 'Electrical rooms', 'Control panels'],
  },
  {
    slug: 'extinguisher-refill-inspection',
    categorySlug: 'refill-service',
    section: 'fire-service',
    name: 'RS-101',
    shortDescription: 'Refill and inspection service',
    description: 'Service program including inspection, refill, pressure check, tagging, and practical reporting.',
    imageUrl: '/assets/fire_tank/fire-training-practice.jpg',
    features: ['On-site planning', 'Refill and readiness tagging', 'Service records for audits'],
    applications: ['Factories', 'Commercial buildings', 'Fleet and warehouse operations'],
  },
];

export const products: Product[] = [...ppeProducts, ...productSeed.filter((product) => product.section === 'fire-service')];

export function findProduct(slug: string | null): Product | undefined {
  return products.find((product) => product.slug === slug);
}

export function findCategory(slug: string): Category | undefined {
  return categories.find((category) => category.slug === slug);
}
